name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: adam
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: projetweb
        ports:
          - 5432:5432

      redis:
        image: redis
        ports:
          - 6379:6379

    env:
      DATABASE_URL: "postgresql://adam:password123@localhost:5432/projetweb"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Apply database migrations
        run: npx prisma migrate deploy

      - name: Lint (ne bloque pas la CI)
        run: |
          npm run lint || echo "❗ ESLint a détecté des erreurs, mais la CI continue."

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Install Newman
        run: npm install -g newman

      - name: Start app in background
        run: |
          npm run start:dev > app.log 2>&1 &
          for i in {1..30}; do
            nc -z localhost 3000 && echo "✅ Server is up!" && break
            echo "⏳ Waiting for server to be ready..." && sleep 1
          done

      - name: Run Postman tests
        run: newman run postman/ProjetWeb.postman_collection.json
