name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: adam
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: projetweb
        ports:
          - 5432:5432

      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Lint (ne bloque pas la CI)
        run: |
          npm run lint || echo "❗ ESLint a détecté des erreurs, mais la CI continue."

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Install Newman and wait-on
        run: |
          npm install -g newman wait-on

      - name: Start app in background
        run: |
          npm run start:dev &
          wait-on http://localhost:3000/health

      - name: Run Postman tests
        run: |
          newman run postman/ProjetWeb.postman_collection.json
